language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - sudo apt-get update && sudo apt-get install uuid-dev

before_script:
  - composer self-update
  - composer install --dev --prefer-source
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then printf "\n" | pecl install uuid; fi;'
  - phpenv rehash

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=phpcs.xml ./

after_script: php vendor/bin/coveralls
